### ISSUE TITLE
jQuery is undefined

### ISSUE THREAD

**Issue by ArthurHoaro** [immanuelfodor/shaarli-markdown-toolbar#1]
I have this issue on both Firefox and Chrome, tested on Shaarli master and v0.9.2, with only `markdown` and `markdown-toolbar` enabled. jQuery doesn't seem to load properly... but the jQuery JS itself is loaded in the network tab.

![screenshot_20180101_153411](https://user-images.githubusercontent.com/1962678/34468449-605d8558-ef09-11e7-91d3-dfea804569b6.png)

**Comment by immanuelfodor** [comment]
It seems the `emojione` plugin added a secondary jQuery to the page that is why it worked for me and not for you. I saw the second jQuery version before this is why I used `jQuery.noConflict()` in the beginning of my plugin's JS but I have forgotten to check the dependency JS file. Now it uses my jQuery version, too. Please check it now, it should work, I managed to reproduce your error and it is fixed by the last commit on my instance.

**Comment by ArthurHoaro** [comment]
Yep, it works fine, well done 👍
